global:
  scrape_interval: 5s 

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'my-demo-app'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['application:80']